import { ImageSourcePropType } from 'react-native';

const images: { [key: string]: ImageSourcePropType } = {
  Logo: require('../Images/Logo.png'),
  Onboarding: require('../Images/Onboarding.png'),
  eye: require('../Images/eye.png'),
  facebookIcon: require('../Images/facebookIcon.png'),
  googleIcon: require('../Images/googleIcon.png'),
  appleIcon: require('../Images/appleIcon.png'),
  continue: require('../Images/continue.png'),
  England: require('../Images/England.png'),
  arrowdown: require('../Images/arrowdown.png'),
  line: require('../Images/line.png'),
  profile: require('../Images/profile.png'),
  backIcon: require('../Images/backIcon.png'),
  rejection: require('../Images/rejection.png'),
  abandonment: require('../Images/abandonment.png'),
  worth: require('../Images/worth.png'),
  homeBase: require('../Images/homeBase.png'),
  mastercard: require('../Images/mastercard.png'),
  closeIcon: require('../Images/closeIcon.png'),
  support: require('../Images/support.png'),
  email: require('../Images/email.png'),
  chat: require('../Images/chat.png'),
  arrow: require('../Images/arrow.png'),
  tick: require('../Images/tick.png'),
  success: require('../Images/success.png'),
  DrawerImg: require('../Images/DrawerImg.png'),
  bell: require('../Images/bell.png'),
  headerprofile: require('../Images/headerprofile.png'),
  background: require('../Images/background.png'),
  Heart: require('../Images/Heart.png'),
  spirtual: require('../Images/spirtual.png'),
  honesty: require('../Images/honesty.png'),
  low: require('../Images/low.png'),
  audio: require('../Images/audio.png'),
  courage: require('../Images/courage.png'),
  forgiveness: require('../Images/forgiveness.png'),
  power: require('../Images/power.png'),
  purpose: require('../Images/purpose.png'),
  excellence: require('../Images/excellence.png'),
  selfimage: require('../Images/selfimage.png'),
  discipline: require('../Images/discipline.png'),
  confidence: require('../Images/confidence.png'),
  selfworth: require('../Images/selfworth.png'),
  respect: require('../Images/respect.png'),
  love: require('../Images/love.png'),
  prosperity: require('../Images/prosperity.png'),
  integrity: require('../Images/integrity.png'),
  happiness: require('../Images/happiness.png'),
};

export default images;
