export const fontFamily: Record<string, string> = {
    UrbanistBlack: 'Urbanist-Black',
    UrbanistBold: 'Urbanist-Bold',
    UrbanistExtraBold: 'Urbanist-ExtraBold',
    UrbanistExtraLight: 'Urbanist-ExtraLight',
    UrbanistLight: 'Urbanist-Light',
    UrbanistMedium: 'Urbanist-Medium',
    UrbanistRegular: 'Urbanist-Regular',
    UrbanistSemiBold: 'Urbanist-SemiBold',
    UrbanistThin: 'Urbanist-Thin',
    GilroyBold: 'Gilroy-Bold',
    GilroyLight: 'Gilroy-Light',
    GilroyMedium: 'Gilroy-Medium',
    GilroyRegular: 'Gilroy-Regular',
    GilroySemiBold: 'Gilroy-SemiBold',
    GilroyThin: 'Gilroy-Thin',
    GIlroyBlack: 'Gilroy-Black',
    GilroyExtraBold: 'Gilroy-ExtraBold',
};
