export const fontFamily: Record<string, string> = {
  UrbanistBlack: 'Urbanist-Black',
  UrbanistBold: 'Urbanist-Bold',
  UrbanistExtraBold: 'Urbanist-ExtraBold',
  UrbanistExtraLight: 'Urbanist-ExtraLight',
  UrbanistLight: 'Urbanist-Light',
  UrbanistMedium: 'Urbanist-Medium',
  UrbanistRegular: 'Urbanist-Regular',
  UrbanistSemiBold: 'Urbanist-SemiBold',
  UrbanistThin: 'Urbanist-Thin',
  GilroyBlack: 'Gilroy-Black',
  GilroyBold: 'Gilroy-Bold',
  GilroyExtraBold: 'Gilroy-ExtraBold',
  GilroyHeavy: 'Gilroy-Heavy',
  GilroyLight: 'Gilroy-Light',
  GilroyMedium: 'Gilroy-Medium',
  GilroyRegular: 'Gilroy-Regular',
  GilroySemiBold: 'Gilroy-SemiBold',
  GilroyThin: 'Gilroy-Thin',
};
